### PR TITLE
UI glitch with narrow devices

### PR DESCRIPTION
**Pull request by MarcelRobitaille**
Fixes: #896

Fix this UI glitch by replacing the [`Breadcrumbs`](https://nextcloud-vue-components.netlify.app/#/Components/Breadcrumbs?id=breadcrumbs-1) element with an element better suited for this kind of button layout. A `ResponsiveActions` was developed based on the [`nextcloud/vue Actions`](https://nextcloud-vue-components.netlify.app/#/Components/Actions?id=actions-1) component. This `ResponsiveActions` shows the buttons with an icon and text if there is enough space, only the icons if there is only enough space for that, and only a 3-dot menu if very narrow devices like phones. This is to avoid  [mystery meat navigation](https://en.wikipedia.org/wiki/Mystery_meat_navigation).

https://user-images.githubusercontent.com/8503756/172550938-d1241efe-cef2-487c-a0bf-79b4e26c2144.mp4

### CODE REVIEW

**Comment by MarcelRobitaille** [comment]
Also, not sure how copying files from nextcloud/nextcloud-vue works. It's GPLV3, so we probably need to state the changes and disclose the source. I'm not sure how that works though, I've never done that before.

[`src/assets/variables.scss`](https://github.com/nextcloud/nextcloud-vue/blob/master/src/assets/variables.scss) and [`src/components/validateSlot.js`](https://github.com/nextcloud/nextcloud-vue/blob/master/src/utils/ValidateSlot.js) are copied unchaged. `ResponsiveActions` is based on [`Actions`](https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/Actions/Actions.vue).

**Comment by christianlupus** [comment]
I just compiled it and found a small further glitch:
grafik

To reproduce:
1. Open recipe for editing. Refresh page to reload any JS code.
2. Scale window such that "folding" begins but text (barely) present
3. Save recipe causing more buttons to appear
4. Rescaling seems to use the with of the original buttons (2 buttons during save) as a boundary for further folding.

**Comment by MarcelRobitaille** [comment]
Thanks for the bug report. I will try to reproduce and fix it.

I understand. I know licensing is tricky. I think it could be made into a PR. My issue requesting this upstream was completely ignored, but maybe a PR would be different.

**Comment by MarcelRobitaille** [comment]
Closing this because I think we're going with #1105

**Pull request closed without merging**
