### PR TITLE
Show error message upon import exception

### PR DESCRIPTION
**Pull request by christianlupus**
This solves partially the issue described in #626 as it avoids an empty alert box.

### CODE REVIEW

**Comment by christianlupus** [comment]
@seyfeb as the original line in the `AppNavi.vue` came from the Axios update,  I just wanted to make sure you are ok with this modification. Or should we check that at least some result was returned before we try to use it.

**Comment by seyfeb** [comment]
> @seyfeb as the original line in the `AppNavi.vue` came from the Axios update, I just wanted to make sure you are ok with this modification. Or should we check that at least some result was returned before we try to use it?

I think there is always some response from the server? To be sure one could provide a default feedback to the user if it’s empty.

**Comment by christianlupus** [comment]
@seyfeb I had a look at the axios documentation once more and came up with a bit more *secure* code in the sense that exceptions are handled more explicitly.

**Comment by seyfeb** [comment]
I think this should be fine, except for the failing linters 😄

**Comment by christianlupus** [comment]
The linters are taken care of.
Good to have them in the CI chain :smile:

**Pull request merged**
