### PR TITLE
Add yield calculator

### LINKED ISSUE #116: Enhancement: Recalculate ingredient quantity (e.g. double it)
Often people want to double or cut in halve the amount that should be cooked or baked.

Suggestion:
Provide the possibility to multiply the amount of ingredient's quantity temporarily.

---

Depends on #340

### PR DESCRIPTION
**Pull request by j0hannesr0th**
This pull request adds a client-side yield calculator to the recipe detail page of every recipe and fixes #116 

@christianlupus I wasn't able to find "how to add translations" in the docu. It's my first contribution to a Nextcloud project and I only found a link to transifex. Can you assist/guide me here please?

The function (without translation) is ready:

Screenshots of the mobile version:
grafik

### CODE REVIEW

**Comment by j0hannesr0th** [comment]
@christianlupus I've added the translation, but I'm not sure if I signed-off correctly. I did not edit the changelog, too.

**Comment by j0hannesr0th** [comment]
@christianlupus the pipeline fails because of code style. If I rund the command `npm run prettier-fix` the translation are being split into multiple lines. What should I do? More translations with less words per translation?

grafik


Should I edit the changelog?

**Comment by christianlupus** [comment]
I can tell you that you signed off correctly. Otherwise, the DCO check would fail.

Regarding the failing prettier test, one has to disable the rule for this single line. See for an example in the code: https://github.com/nextcloud/cookbook/blob/a8093344ac72dfe773e26856dcba5df836941944/src/components/RecipeView.vue#L22-L23

**Comment by j0hannesr0th** [comment]
@christianlupus ok, codestyle should be fixed. What about the changelog?

**Comment by christianlupus** [comment]
Just add an entry to the added section (create one if needed) in the CHANGELOG.md file. That should do it.

**Comment by j0hannesr0th** [comment]
@christianlupus merge conflicts resolved.

**Comment by j0hannesr0th** [comment]
@christianlupus all checks ran successful now. Can you test and merge it please that no merge conflicts must be resolved again?

Thanks!

**Comment by christianlupus** [comment]
I already had a quick glance. I wanted to test manually a few more cases and did find one minor thing so far. Will fix and merge or come back to you.

**Comment by christianlupus** [comment]
I just checked a few additional cases. Now, I found a few issues, that might come up in the close future (or to help enhance the code base). I will nevertheless approve/merge this PR to get the functionality into the app. The fixes can then be applied step by step.

I will open a new bug with all found issues in order to tackle them.

**Review by christianlupus — APPROVED** [review]

**Comment by MrLoverLoverMMMM** [comment]
With which version will this be released?

**Comment by christianlupus** [comment]
This should be in the next release 0.10.3.

**Pull request merged**
