### PR TITLE
Add tooltips to buttons on the control row

### LINKED ISSUE #280: Papercut: Some icons have a tooltip, , others have no tooltip
**Description**
Some icons have a tooltip, , others have no tooltip.
In the left sidebar there are tooltips, in top breadcrumbs  navigation are no tooltips

**Expected behavior**
All icons should have a tooltip 

**Screenshots**
icons with tooltip are marked light blue
icons without tooltip are marked dark blue
cb20202627

**probably**
Some icons have a title attribute , others have an adria-label attribute.

**Versions**
Firefox: 77.0.1
Cookbook: 0.7.6

### PR DESCRIPTION
**Pull request by sam-19**
Resolves #280

### CODE REVIEW

**Comment by mrzapp** [comment]
@sam-19 did you not accept the collaborator invitation I sent a while back? The repo has now been transferred to the official NextCloud group, so I can't reissue it.

It would be easier if you could just commit your patches directly to the master branch

**Comment by sam-19** [comment]
Hey! I can't find any email alert from Github about that, so I must have missed it. Sorry! I know pull requests are an additional manual step in the workflow, but they do offer a forum for discussion about the proposed changes (like the changed locale string in this one).

**Comment by MorrisJobke** [comment]
> I use GitLab as my personal repository server and Github only quite occasionally, so I don't know how to fix the missed invitation. I'll tag one active member from the Nextcloud organization (@MorrisJobke, sorry for the trouble!) who maybe has the needed privileges or can tell someone who does.

I invited you both to the nextcloud organization. :)

**Comment by sam-19** [comment]
Thank you, @MorrisJobke! My rebase kind of went to hell with this branch, so I'm going to ditch this one and make a new pull request.

**Pull request closed without merging**
