### PR TITLE
Create .gitkeep

### PR DESCRIPTION
**Pull request by rakekniven**
Signed-off-by: rakekniven <mark.ziegler@rakekniven.de>

### CODE REVIEW

**Comment by christianlupus** [comment]
May I ask why a `.gitkeep` file is needed? There is already a `.dummy` file that will avoid an empty folder been deleted by git if all translations would have been removed (which is quite uncommon).

**Comment by rakekniven** [comment]
> May I ask why a `.gitkeep` file is needed? There is already a `.dummy` file that will avoid an empty folder been deleted by git if all translations would have been removed (which is quite uncommon).

See the docs. The Nextcloud project want keep the same structure for all repos. For sure we can rename the dummy file as well.

**Comment by rakekniven** [comment]
Should I modify my PR?

**Comment by christianlupus** [comment]
I just did so. Will merge directly.

**Pull request merged**
