### PR TITLE
Show nutritional infos of recipe and make them editable

### LINKED ISSUE #185: Feature Request : extra fields
Hi,
Many thanks for this great apps.
I am able to import automatically many saved page from cookido/thermomix site where I own an account (I have tried with ~20 recipes so far).

I have noticed that extra areas exist like nutritional informations, advice,tips an usefool accessories areas are part of the recipe description and are not imported as of today.

Does it make sense to think about them and have assocated field/data taken into account and imported as well ?
Attached screenshots from what I get with original saved page and imported one within NC 18.0.3. and 0.6.3 app.
2020-04-03 10_37_32-Livre de recettes - Fwatc
2020-04-03 10_36_19-Cookidoo® - Tartare de saumon frais

[view-source.txt](https://github.com/mrzapp/nextcloud-cookbook/files/4425968/view-source.txt)

### LINKED ISSUE #225: Add additional schema.org fields
Could we have more schema.org fields? Specifically what I'm interested in is nutrition info.

### PR DESCRIPTION
**Pull request by seyfeb**
Made nutrition information visible in the UI.

To test viewing the information, you can import some recipe, e.g., <https://www.taste.com.au/recipes/seared-kangaroo-raspberry-glaze/8179a9df-2188-4050-adea-2163424650ed?r=recipes/nutritioninformation>

I also added an editing component for nutrition information. 

@sam-19: It would be great, if you could review this PR!

Closes #185, closes #225 

**Viewing nutrition information**

Screenshot 2020-11-29 at 16 22 05

**Editing nutrition information**

Screenshot 2020-11-29 at 16 21 34

### CODE REVIEW

**Review by christianlupus — APPROVED** [review]
The backend looks good and the frontend seems to be ok in the frontend.

**Comment by seyfeb** [comment]
Update: Labels are now be provided that are shown instead of the nutrition infos json keys. Also the options passed to `EditMultiselectInputGroup` are now easier to read, imho.

**Comment by sam-19** [comment]
Great idea! 👍 If it works, go for it :)
(My comment about the value prop from #386 still applies)

**Comment by christianlupus** [comment]
I opened a PR against your branch, @seyfeb. I find it strange to have a heading without any sort of content. Apart from that, I do not see any issues here. So please either merge the PR seyfeb/cookbook#17, come up with your own solution or state to merge nontheless.

**Review by christianlupus — APPROVED** [review]

**Comment by hoshsadiq** [comment]
Thank you guys. This will be a great addition! Much appreciated.

**Pull request merged**
