### PR TITLE
Allow selecting recipes with unassigned category

### LINKED ISSUE #326: 'None' category selection
when i am importing several recipies, i sometimes loose track on which categories I have added the new recipies to.  it ends up being time consuming to track down those items that are not categorized yet.  is there a way to add a filter for uncategorized recipies?

### PR DESCRIPTION
**Pull request by seyfeb**
Added item for viewing uncategorized recipes in the navigation.

Closes #326

### CODE REVIEW

**Comment by christianlupus** [comment]
I just had a quick look at the changes. In fact I have a bit of a bad feeling here. Apart from the fact that using an arbitrary symbol as a special value for no category, I found these lines: [[1](https://github.com/nextcloud/cookbook/blob/master/src/components/AppNavi.vue#L243-L245)], [[2](https://github.com/nextcloud/cookbook/blob/master/lib/Db/RecipeDb.php#L434-L437)]. These are using a star as symbol (neither really good).

I have to admit, that I have not yet tested the changes.

My suggestion is to stick with either symbol (makes no difference to me). Then in #332, #299 and #365 there is the chance to define a more stable API. Any comments/suggestions on that by anyone?

**Comment by seyfeb** [comment]
I have seen the `*` being used as well, but had the feeling using this would be even worse. I would rather interpret it as a wildcard, matching every category. I didn’t want to break anything else though, so I just used `_` as a proposal. 

Obviously this would conflict with a category named “_”, so a new API endpoint might be helpful. I didn’t want to start on this as @christianlupus was discussing API changes somewhere else, anyway, if I remember correctly.

**Comment by christianlupus** [comment]
You remember correctly, apart from #342 I was considering to do quite some backend refactory. If you do not mind that these changes are overwritten soon, I'd test them and merge until the more thorough rework is finished.

**Comment by seyfeb** [comment]
No that’s fine. I just thought it might be nice to have this option even "sooner" ;) And to close the corresponding issue.

**Comment by christianlupus** [comment]
OK, a quick test shows that it seems to work so far. Will merge that and hope for the best. :smile:

**Pull request merged**
